services:
  server:
    build: .
    pull_policy: build
    restart: unless-stopped
    networks:
      - public-apps
    labels:
      traefik.enable: true
      traefik.http.routers.piss.rule: Host(`piss.lenn.rocks`) # set router name and subdomain
      traefik.http.services.piss.loadbalancer.server.port: 80 # set port that is forwarded to internally to (80 is nginx default)


networks:
  public-apps:
    external: true # hook into public network instead of creating our own
